### PR TITLE
Message cleanup callbacks

### PR DESCRIPTION
**Pull request by S-S-X**
Did not test anything as I wrote these in github editor, there might very well be typos and it might just crash or not work at all or mess up everything or might also just work...

Also http message cleaner to cleaner.lua, adds `  > ` after line feeds.

edit. Tested and added bit more stuff:
* Fix some feedback messages not sent for jailed players, /whis command for example
* Add some missing feedback messages for jailed players, channel switching
* Simplify common callback usage
* Moved things that are required for core functionality to plugin directory
* Added override for command block /tell command to execute callbacks
* Added full whitespace cleanup for messages received through HTTP polling

### CODE REVIEW

**Comment by OgelGames** [comment]
Looks like it should work to me 👍

**Comment by S-S-X** [comment]
Tested a bit and basically works but there's small bug preventing all channel messages:
```diff
-- channel_name = msg_data.channel_name
++ channel_name = msg_data.channel
```

I think I'll add few more callback fixes and override for `/tell` now that I started testing it a bit, already fixed few small bugs / inconsistencies and committing soon.

**Comment by S-S-X** [comment]
I think everything works fine, tested some stuff like multiple commands and HTTP messages. Did not test HTTP commands but those should not be affected at all.
I think this is good enough for merge so going forward.

**Comment by BuckarooBanzay** [comment]
nice work :+1:

**Pull request merged**
