### PR TITLE
Callback API

### PR DESCRIPTION
**Pull request by S-S-X**
This PR adds callback API and implements @SwissalpS's chat jail through callbacks.

Callback do work in general but there's still some issues:
* Not tested well, only some partial very basic testing done.
* Fires some unnecessary duplicate callbacks: https://github.com/S-S-X/beerchat/issues/2
* Comments on callback behavior? IMO there should be specialization for some callback like check_muted, it does not fit very well in general return value handling.
* Currently callbacks allow aborting whole chain processing, there should be some way to add "execute always" callbacks. Most flexible way would be to return table with behavior instructions but easily gets out of control and callback handling should be as lightweight as possible.
* There's some "cosmetic" issues like jailed users can say "#main hello" and message will be dropped to jail as is as long as sender is jailed. This is just example of what is probably caused by duplicate callbacks issue mentioned above ^^.

That said, I think this is good enough for merging into master. Nobody forces you to use it for anything but "chat jail".
It would be better for overall development progress to merge now and start fixing bugs / updating features as smaller commits.

**Would be very nice if someone could test this better if there's showstoppers like hard crashes**
But for other smaller non fatal issues that do not break basic usage (channels, PMs, existing commands, etc.) I'd suggest merging anyway and open new issues for those.

Please provide some constructive feedback on this before merging **or** closing this PR.

### CODE REVIEW

**Comment by SwissalpS** [comment]
did not crash for me either after some basic tests

**Comment by thomasrudin** [comment]
Where do i find the jail commands again...? Did i miss something?

**Comment by SwissalpS** [comment]
> Where do i find the jail commands again...? Did i miss something?

you need to activate jail functions after SX's refactor.
Have not tested all functions myself yet either.

**Comment by S-S-X** [comment]
@thomasrudin 

> Where do i find the jail commands again...? Did i miss something?

* `beerchat.enable_jail` https://github.com/S-S-X/beerchat/blob/83ffafa7d380b656d19ce5674c60f36ba1f54ec4/init.lua#L71
* `/force2channel <channel>, <player>` https://github.com/S-S-X/beerchat/blob/83ffafa7d380b656d19ce5674c60f36ba1f54ec4/chatcommands.lua#L438-L444
* `/chat_jail <player1> <player2> ...` https://github.com/S-S-X/beerchat/blob/83ffafa7d380b656d19ce5674c60f36ba1f54ec4/jail.lua#L47-L53
* `/chat_unjail <player1> <player2> ...` https://github.com/S-S-X/beerchat/blob/83ffafa7d380b656d19ce5674c60f36ba1f54ec4/jail.lua#L77-L83

**Comment by SwissalpS** [comment]
the default jail-channel is now #grounded no longer #wail

**Comment by SwissalpS** [comment]
@S-S-X I have submitted a PR to your fork fixing a minor bug and also cleaning up code so that
luacheck passes. Some warnings remain about unused variables.

**Comment by S-S-X** [comment]
@SwissalpS here is better view to those 2 commits I cherry picked from you PR.

To keep merges cleaner I suggest that other code style fixes would go into separate PR directly to upstream (this repository where this PR is open) because those are changing mostly things that are already pushed or merged into minetest-beerchat/beerchat repository.

Cherry-picked commits will be skipped (as already merged) when you open PR here as those are exact hashes from you repository.

You can open PR immediately but to avoid merge conflicts this PR must be merged first as you used S-S-X/beerchat/tree/master as base for those commits.

**Comment by thomasrudin** [comment]
LGTM, feel free to merge :+1:

**Pull request merged**
