### PR TITLE
Basic plugin system

### LINKED ISSUE #18: Use single entry point for chat messages
### What:
Update things like whisper, sending to channel and channel switching to use single entry point instead of multiple.
That means only single `minetest.register_on_chat_message` should exists in mod and that should take care of routing.

### Why:
Whisper, channels, etc. can then be converted to extensions and that should allow better structure for both future and existing functionality.
Basically this is to allow isolating beerchat core functionality which should be just routing API from additional functionality, bells and whistles provided by loadable extensions.

Just because it is somewhat related: https://github.com/pandorabox-io/pandorabox.io/issues/455

### PR DESCRIPTION
**Pull request by S-S-X**
Transform most "core" chat functionality into isolated extensions and uses single entry point for chat message handling.
Closes #18 

These are moved, check after tested
- [x] pm `@player hello world` and `/msg player hello world`
- [x] whisper `$ hello world` and `$50 hello world`
- [x] hash `#channel` and `#channel hello world`
- [x] me `/me hello world`

Todo
- [x] Requires merging changes from #32 or will crash during loading
- [x] Remove on_mods_loaded hack from default message handler

### CODE REVIEW

**Comment by S-S-X** [comment]
Whispering `$150 Hello world` works but also prints command to chat so result what players see is
`|#main| <SX> whispers: $150 Hello world`
It should drop `$150 ` from message.

**Comment by S-S-X** [comment]
Noticed that this also fixes case where whisper radius is more than max radius: in addition to error message whole chat line was printed to main channel.
This PR seems to fix that too to not print to main if radius is larger than max and will correctly still print error message.

**Comment by S-S-X** [comment]
Also fixes `on_receive` callback possibly executed multiple times in certain situations, so far nothing got actually affected by this but there's no reason to go through it more than once when message is received.

That on_mods_loaded hack must be fixed or `error` removed from end of main message handler in `router.lua`, before that is done if player without `shout` privilege send message it will crash server with `Beerchat was unable to handle message: ...`. Added that error just for easy testing if anything falls through.

**Comment by S-S-X** [comment]
Some code changes to whispering, tested functionality again and seems to work just fine.
Everything seems to be fine.

@BuckarooBanzay how does structure/changes look for you? Good enough?

My personal opinion: Even while this is not bringing complete API or automated plugin loading I think this is better for development than everything in large pile.

**Comment by BuckarooBanzay** [comment]
> @BuckarooBanzay how does structure/changes look for you? Good enough?

they involve a bit more "magic" than just plain `dofile` calls but that will work in this case :+1: 

> My personal opinion: Even while this is not bringing complete API or automated plugin loading I think this is better for development than everything in large pile.

Better something imperfect now than something perfect _someday_ :)

**Comment by S-S-X** [comment]
Then sounds good enough 😄

**Pull request merged**
